name: Create Pull Request to Main

on:
  push:
    branches:
      - 'sw**'
      - 'cm**'
      
jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.ref_name }}
          target_branch: main
          title: "Auto PR: ${{ github.ref_name }} → main"
          body: |
            이 PR은 `${{ github.ref_name }}` 브랜치에서 자동 생성되었습니다.
          draft: false
          delete_branch: false
